test_format = 1.0

[default]

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.c5cf91ad.name = "Upgrade from 25.0.2"
    


